const constants = {
    FETCH_AUTOCOMPLETE_CITIES: 'FETCH_AUTOCOMPLETE_CITIES',
    FETCHED_AUTOCOMPLETE_CITIES: 'FETCHED_AUTOCOMPLETE_CITIES',
    FETCHING_AUTOCOMPLETE_CITIES: 'FETCHING_AUTOCOMPLETE_CITIES'
};

export default constants;
